language: rust

sudo: true

rust:
    - "1.40.0"
    - "stable"
    - "beta"
    - "nightly"

jobs:
    allow_failure:
        - rust: "nightly"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y python3

script:
    - make test
