language: rust

sudo: true

rust:
    - "1.41.1"
    - "1.43.0"
    - "1.43.1"
    - "1.44.1"
    - "1.45.2"
    - "1.46.0"
    - "1.47.0"
    - "stable"
    - "beta"
    - "nightly"

jobs:
    allow_failures:
        - rust: "nightly"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y python3

script:
    - make test
