language: rust

sudo: true

rust:
    - "stable"
    - "beta"
    - "nightly"

matrix:
    allow_failure:
        - rust: "nightly"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y valgrind python3

script:
    - make test
