language: rust

sudo: true

rust:
    - "1.32.0"
    - "1.33.0"
    - "1.34.2"
    - "1.35.0"
    - "1.36.0"
    - "stable"
    - "beta"
    - "nightly"

matrix:
    allow_failure:
        - rust: "1.32.0"
        - rust: "nightly"

before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -y valgrind python3

script:
    - make test
