no-dev-version = true
pre-release-commit-message = "LibreAuth version {{version}}"
pre-release-hook = ["make", "clean", "audit", "test"]
pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
]
tag-message = "LibreAuth version {{version}}"

# https://github.com/sunng87/cargo-release/blob/master/docs/reference.md
# Be aware that `pro-release-commit-message` may have been renamed.
# When it will become possible to bump to a development version, set `no-dev-version` to false and uncomment the following.

# dev-version-ext = "dev"
# pro-release-commit-message = "Starting LibreAuth version {{next_version}}"
